INSERT INTO breeds (species, breed_name) VALUES
(TRUE, 'Mestizo'),
(TRUE, 'Chihuahua'),
(TRUE, 'Schnauzer'),
(TRUE, 'Pitbull'),
(TRUE, 'Poodle'),
(TRUE, 'Labrador Retriever'),
(TRUE, 'Pug'),
(TRUE, 'Pastor Alemán'),
(TRUE, 'Golden Retriever'),
(TRUE, 'Yorkshire Terrier'),
(TRUE, 'Doberman'),
(TRUE, 'Husky Siberiano'),
(TRUE, 'Rottweiler'),
(TRUE, 'Bóxer'),
(TRUE, 'Shih Tzu'),
(TRUE, 'Teckel'),
(TRUE, 'Beagle'),
(TRUE, 'Bulldog Francés'),
(TRUE, 'Bulldog Inglés'),
(TRUE, 'Braco Alemán de Pelo Corto'),
(TRUE, 'Pastor Australiano'),
(TRUE, 'Cavalier King Charles Spaniel'),
(TRUE, 'Cane Corso'),
(TRUE, 'Corgi Galés de Pembroke'),
(TRUE, 'Schnauzer Miniatura'),
(TRUE, 'Boyero de Berna'),
(TRUE, 'Gran Danés'),
(TRUE, 'Pomerania'),
(TRUE, 'Boston Terrier'),
(TRUE, 'Bichón Habanero'),
(TRUE, 'Pastor de Shetland'),
(TRUE, 'Bretón'),
(TRUE, 'Cocker Spaniel'),
(TRUE, 'Malinois Belga'),
(TRUE, 'Basset Hound'),
(TRUE, 'Braco Húngaro'),
(TRUE, 'Bichón Maltés'),
(TRUE, 'Collie'),
(TRUE, 'West Highland White Terrier'),
(TRUE, 'Shiba Inu'),
(TRUE, 'Crestado Rodesiano'),
(TRUE, 'Papillón'),
(TRUE, 'Perro de Agua Portugués'),
(TRUE, 'Bichón Frisé'),
(TRUE, 'Terranova'),
(TRUE, 'Dálmata'),
(TRUE, 'Boyero Australiano'),
(TRUE, 'Whippet'),
(TRUE, 'Border Collie'),
(TRUE, 'San Bernardo'),
(FALSE, 'Mestizo'),
(FALSE, 'Siamés'),
(FALSE, 'Persa'),
(FALSE, 'Americano de Pelo Corto'),
(FALSE, 'Bombay'),
(FALSE, 'Ragdoll'),
(FALSE, 'Maine Coon'),
(FALSE, 'Esfinge'),
(FALSE, 'Británico de Pelo Corto'),
(FALSE, 'Abisinio'),
(FALSE, 'Bengalí'),
(FALSE, 'Fold Escocés'),
(FALSE, 'Devon Rex'),
(FALSE, 'Exótico de Pelo Corto'),
(FALSE, 'Azul Ruso'),
(FALSE, 'Siberiano'),
(FALSE, 'Bosque de Noruega'),
(FALSE, 'Birmano'),
(FALSE, 'Oriental de Pelo Corto'),
(FALSE, 'Burmés'),
(FALSE, 'Himalayo'),
(FALSE, 'Mau Egipcio'),
(FALSE, 'Bobtail Americano'),
(FALSE, 'Angora Turco'),
(FALSE, 'Manx'),
(FALSE, 'Cornish Rex'),
(FALSE, 'Tonkinés'),
(FALSE, 'Cartujo'),
(FALSE, 'Balinés'),
(FALSE, 'Ocicat'),
(FALSE, 'Somalí'),
(FALSE, 'Bobtail Japonés'),
(FALSE, 'Pardo de la Habana'),
(FALSE, 'Korat'),
(FALSE, 'Burmilla'),
(FALSE, 'Singapura'),
(FALSE, 'Ragamuffin'),
(FALSE, 'Selkirk Rex'),
(FALSE, 'LaPerm'),
(FALSE, 'Van Turco'),
(FALSE, 'Nebelung'),
(FALSE, 'Pixie-bob'),
(FALSE, 'Toyger'),
(FALSE, 'Chausie'),
(FALSE, 'Peterbald'),
(FALSE, 'Savannah'),
(FALSE, 'Serengeti'),
(FALSE, 'Gato de Chipre'),
(FALSE, 'Mau Árabe');
