ALTER TABLE IF EXISTS pets
    ADD COLUMN IF NOT EXISTS has_other_pets BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS pet_label SMALLINT DEFAULT NULL;

ALTER TABLE IF EXISTS pets
    RENAME COLUMN shading_level TO shedding_level;